ContractLab/ContractLab.UI/Controllers/IsolatesController.cs
using ContractLab.DTO;
using ContractLab.UI.Models.ContractLab;
using ContractLab.DataService.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Yahara.ServiceInfrastructure.Messages;
using Microsoft.AspNet.Identity;

namespace ContractLab.UI.Controllers
{
    [Authorize]
    public class IsolatesController : Controller
    {
        private const string _fieldlist = @"Id, PassageLevel, DateHarvested, Titer, RedBloodCellType, SpecimenId, IsolateTypeId, CSID, Comments, StatusId";

        private readonly IContractLabDataService  _dataService;
        public IsolatesController(IContractLabDataService dataService)
        {
            _dataService = dataService;
        }

        // GET: Isolates
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
         
            var uro = _dataService.UserReadOnly().Success;
            var uie = _dataService.UserEditor().Success;

            ViewBag.AllowC = _dataService.UserHasLab().Success;

            ViewBag.SpecimenId = id.Value;
            var vm = new List<IsolateVM>();
            var dto = _dataService.IsolateList(new MessageBase<int>() { Data = id.Value});
            if (dto.Success)
            {
                var Isolates = dto.Data as List<IsolateDTO>;
                var selectedList = (TempData["SelectedItems"] as List<int>);
                if (selectedList == null)
                {
                    Isolates.ForEach(e => vm.Add(new IsolateVM(e, uro, uie)));
                }
                else
                {
                    Isolates.ForEach(e => { var tempSVM = new IsolateVM(e, uro, uie); tempSVM.Selected = selectedList.Contains(e.Id); vm.Add(tempSVM); });
                }
                if (TempData.ContainsKey("DialogTitle"))
                {
                    ViewBag.DialogTitle = TempData["DialogTitle"];
                }
                if (TempData.ContainsKey("DialogBody"))
                {
                    ViewBag.DialogBody = TempData["DialogBody"];
                }
                if (TempData.ContainsKey("DialogSuccess"))
                {
                    ViewBag.DialogSuccess = TempData["DialogSuccess"];
                }               
            }
            return View(vm);
        }

        // GET: Isolates/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            IsolateVM vm = null;
            var dto = _dataService.Isolate(new MessageBase<int>(){ Data = id.Value });
            if (dto.Success)
            {
                var uro = _dataService.UserReadOnly().Success;
                var uie = _dataService.UserEditor().Success;
                vm = new IsolateVM(dto.Data, uro, uie);
            } else
            {
                return HttpNotFound();
            }
            return View(vm);
        }

        // GET: Isolates/Create
        public ActionResult Create(int? id)
        {
            //ViewBag.UserId = new SelectList(db.AspNetUsers, "Id", "Email");
            //ViewBag.StatusId = new SelectList(db.Status, "Id", "SysName");
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }


            GetCreateRequiredData();

            var spec = _dataService.Specimen(new MessageBase<int>() { Data = id.Value });
            var csid = string.Empty;
            var subtype = string.Empty;
            if (spec.Success)
            {
                csid = spec.Data.CSID;
                subtype = spec.Data.SubType;
            }
            var vm = new IsolateVM() { SpecimenId = id.Value, CSID = csid, SubType = subtype };
            ViewData.Model = vm;
            return View();
        }

        private void GetCreateRequiredData()
        {
            var rbctList = new List<NameValueDTO>();
            rbctList.Add(new NameValueDTO());
            rbctList.Add(new NameValueDTO() { Name = "TRBC", Value = "TRBC" });
            rbctList.Add(new NameValueDTO() { Name = "GPRBC", Value = "GPRBC" });
            rbctList.Add(new NameValueDTO() { Name = "GPRBC-OSEL", Value = "GPRBC-OSEL" });

            ViewBag.RedBloodCellType = new SelectList(rbctList, "Value", "Value");

            var isolatetypes = _dataService.IsolateTypeList().Data;
            if (isolatetypes == null)
            {
                isolatetypes = new List<IsolateTypeDTO>();
            }
            else
            {
                isolatetypes = isolatetypes.Where(s => s.IsVisible).ToList();
            }
            ViewBag.IsolateTypeId = new SelectList(isolatetypes, "Id", "DisplayName", isolatetypes.Where(s => s.SysName.Equals("GROWN")).FirstOrDefault().Id);

            //var statusList = _dataService.StatusList().Data;
            //if (statusList == null)
            //{
            //    statusList = new List<NameValueDTO>();
            //}
            //ViewBag.StatusId = new SelectList(statusList, "Value", "Name");

            var statusChangeList = _dataService.StatusDTOList();
            if (statusChangeList.Success)
            {
                var tempList = statusChangeList.Data;
                if (!User.IsInRole("Admin"))
                {
                    var tempItem = tempList.FirstOrDefault(s => s.SysName == "SUBMITTED");
                    if (tempItem != null)
                    {
                        tempList.Remove(tempItem);
                    }
                }
                ViewBag.StatusId = new SelectList(statusChangeList.Data, "Id", "DisplayName", tempList[0].Id);
            }
            
        }

        // POST: Isolates/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = _fieldlist)] IsolateVM vm)
        {
            if (ModelState.IsValid)
            {
                var dto = new IsolateDTO {
                    PassageLevel = vm.PassageLevel,
                    DateHarvested = vm.DateHarvested,
                    Titer = vm.Titer,
                    RedBloodCellType = vm.RedBloodCellType,
                    SpecimenId = vm.SpecimenId, 
                    IsolateTypeId = vm.IsolateTypeId,
                    Comments = vm.Comments,
                    StatusId = vm.StatusId.HasValue && vm.StatusId > 0 ? vm.StatusId : null,
                };
                var Isolate = _dataService.IsolateInsert(new MessageBase<IsolateDTO>() { Data = dto });
                if (Isolate.Success)
                {
                    return RedirectToAction("Index", new { id = vm.SpecimenId });
                }
                else
                {
                    ModelState.AddModelError("", Isolate.GetDetailedErrorString());
                }
            }
            GetCreateRequiredData();
            var spec = _dataService.Specimen(new MessageBase<int>() { Data = vm.SpecimenId });
            var csid = string.Empty;
            if (spec.Success)
            {
                csid = spec.Data.CSID;
                vm.CSID = csid;
            }
            return View(vm);
        }

        // GET: Specimens/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            IsolateVM vm = null;
            var dto = _dataService.Isolate(new MessageBase<int>() { Data = id.Value });
            if (dto.Success)
            {

                if (dto.Data.HasRCVAliquot)
                {
                    ViewBag.DialogTitle = "Edit Subsample";
                    ViewBag.DialogBody = String.Format("Warning: Do not edit an original subsample to add GROWN, ITT or VNR data. Add a new subsamples to add these data.");
                    ViewBag.DialogSuccess = "Close";
                }

                var uro = _dataService.UserReadOnly().Success;
                var uie = _dataService.UserEditor().Success;
                vm = new IsolateVM(dto.Data, uro, uie);
                GetCreateRequiredData(vm);

            }
            else
            {
                return HttpNotFound();
            }

            return View(vm);
        }

        private void GetCreateRequiredData(IsolateVM vm)
        {
            var rbctList = new List<NameValueDTO>();
            rbctList.Add(new NameValueDTO());
            rbctList.Add(new NameValueDTO() { Name = "TRBC", Value = "TRBC" });
            rbctList.Add(new NameValueDTO() { Name = "GPRBC", Value = "GPRBC" });
            rbctList.Add(new NameValueDTO() { Name = "GPRBC-OSEL", Value = "GPRBC-OSEL" });

            ViewBag.RedBloodCellType = new SelectList(rbctList, "Value", "Value", vm.RedBloodCellType);

            var isolatetypes = _dataService.IsolateTypeList().Data;
            if (isolatetypes == null)
            {
                isolatetypes = new List<IsolateTypeDTO>();
            }
            else
            {
                isolatetypes = isolatetypes.Where(s => s.IsVisible || s.Id == vm.IsolateTypeId).ToList();
            }
            ViewBag.IsolateTypeId = new SelectList(isolatetypes, "Id", "DisplayName", vm.IsolateTypeId);

            //var statusList = _dataService.StatusList().Data;

ContractLab/ContractLab.UI/Views/Aliquots/Create.cshtml
@model ContractLab.UI.Models.ContractLab.AliquotVM

@{
    ViewBag.Title = "Aliquots";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Aliquot</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.IsolateId, new { htmlAttributes = new { @class = "form-control" } })

        @*<div class="form-group">
            @Html.LabelFor(model => model.CUID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CUID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CUID, "", new { @class = "text-danger" })
            </div>
        </div>*@
        <div class="form-group">
            @Html.LabelFor(model => model.CSID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CSID, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CSID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SubType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.SubType, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SubType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TestCode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TestCode", null, htmlAttributes: new { @autofocus = "autofocus", @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TestCode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ManifestId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ManifestId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ManifestId, "", new { @class = "text-danger" })
            </div>
        </div>

@if (User.IsInRole("Admin"))
{
    <div class="form-group">
        @Html.LabelFor(model => model.StatusId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StatusId", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
        </div>
    </div>
}
else
{
    <div class="form-group">
        @Html.LabelFor(model => model.StatusId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("StatusId", null, htmlAttributes: new { @disabled = "disabled", @class = "form-control" })
            @Html.ValidationMessageFor(model => model.StatusId, "", new { @class = "text-danger" })
        </div>
    </div>
}

        <div class="form-group">
            @Html.LabelFor(model => model.IsStoredLocally, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsStoredLocally, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsStoredLocally, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<p>
    Enter the test code of “REF” for the aliquot designated for the reference laboratory.
</p><p>
    Enter the test code of “RHI” for the aliquot designated for the HI test.
</p><p>
    Enter the test code of “RPS” for the aliquot designated for permanent storage.
</p><p>
    Enter the test code of “MET” for the aliquot designated for molecular epidemiology testing.
</p><p>
    Enter the test code of “ISA” for the aliquot designated for the Influenza Sequencing Activity group. (Isolate)
</p><p>
    Enter the test code of “ISR” for the aliquot designated for the Influenza Sequencing Activity group. (Original Sample)
</p><p>
    Enter the test code of “RCV” for the original sample aliquot.
</p>
<p>
    Enter the test code of “NAI” for the aliquot designated for the Neuraminidase inhibition test.
</p>
    <div>
        @Html.ActionLink("Back to List", "Index", new { id = Model.IsolateId })
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ContractLab")
    @Scripts.Render("~/bundles/jquery-easyui")
    <script>
        function initialize() {
            $('#TestCode').change(function () {
                var codes = "@ViewBag.LocalTestCodes";
                var codeArray = codes.split(",");
                if ($.inArray($(this).val(), codeArray) >= 0 ) {
                    $('#IsStoredLocally').prop('checked', true);
                } else
                {
                    $('#IsStoredLocally').prop('checked', false);
                };
            });
        };
        initialize();
    </script>
}

ContractLab/ContractLab.UI/Views/Aliquots/Delete.cshtml
@model ContractLab.UI.Models.ContractLab.AliquotVM

@{
    ViewBag.Title = "Aliquots";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Aliquot</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CSID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CSID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CUID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CUID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TestCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TestCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Manifest)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Manifest)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsStoredLocally)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsStoredLocally)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(model => model.IsolateId, new { htmlAttributes = new { @class = "form-control" } })
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", new { id = Model.IsolateId })
        </div>
    }
</div>

ContractLab/ContractLab.UI/Views/Aliquots/Details.cshtml
@model ContractLab.UI.Models.ContractLab.AliquotVM

@{
    ViewBag.Title = "Aliquots";
}

<h2>Details</h2>

<div>
    <h4>Aliquot</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CSID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CSID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.SubType)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.SubType)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CUID)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CUID)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TestCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TestCode)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Manifest)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Manifest)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsStoredLocally)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsStoredLocally)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index", new { id = Model.IsolateId })
</p>

ContractLab/ContractLab.UI/Views/Aliquots/Index.cshtml
@model IEnumerable<ContractLab.UI.Models.ContractLab.AliquotVM>

@{
    ViewBag.Title = "Aliquots";
}

<h2>Aliquot Information</h2>
@if (ViewBag.AllowC)
{
<p>
    <table>
        <tr>
        <td style="padding-left: 20px">
            @Html.ActionLink("Create New", "Create", new { id = ViewBag.IsolateId })
</td>
            <td style="padding-left: 20px" >
@using (Html.BeginForm("CreateMultiple", "Aliquots", FormMethod.Post, new { id = "CreateMultipleForm" }))
{
    @Html.Hidden("IsolateId", (object)ViewBag.IsolateId)
    if (ViewBag.AllowC)
    {
        <table><tr><td>@Html.DropDownList("ManifestId", null, htmlAttributes: new { @class = "form-control", style = "display:inline;" })</td><td style="padding-left: 20px"><input type="submit" value="Create Grown Set" name ="GROWN" class="btn btn-default" /><td style="padding-left: 20px"><input type="submit" value="Create ITT Set" name="ITT" class="btn btn-default" /></td></tr></table>
    }
}</td>
        </tr>
    </table>    
</p>
    

}


<script>

    function onDownloadClick(sourceName) {
        $('input[name^="submitDL"]')  // for all checkboxes
        .each(function () {
            $(this).remove();
        })
        $('<input/>').attr('type', 'hidden').attr('name', sourceName).attr('value', 1).appendTo('#MultiActionForm');
        $('#MultiActionForm').submit();
    }

    function onPrintClick(sourceName) {
        $('#submitPLP').remove();
        $('#' + sourceName).remove();
        var sourceInput = $('<input>').attr({
            type: 'hidden',
            id: sourceName,
            name: sourceName,
            value: sourceName
        });
        $('#MultiActionForm').append(sourceInput);
        $('.alert').hide();
        $.ajax({
            type: "POST",
            url: "@Url.Action("MultiAction", "Aliquots")",
            data: $('#MultiActionForm').serialize(),
        datatype: "html",
        success: function (data) {
            //$.ajaxSettings.traditional = true;
            $.ajax({
                contentType: "application/json; charset=utf-8",
                type: "POST",
                url: data.url,
                data: JSON.stringify(data),
                datatype: "json",
                success: function (dataP) {
                    $("#checkboxes input").each(function () {
                        $(this).prop("checked", false);
                    });
                },
                error: function (respE) {
                    $('#printerrortext').text("Error communicating to printer bridge");
                    $('.alert').show();
                }
            });
        },
        error: function () {
            $('#printerrortext').text("Error getting label information from server");
            $('.alert').show();
        }
    });
    }

    function onPrintClick_Dialog(sourceName) {
        $('#submitPL').remove();
        $('#' + sourceName).remove();
        var sourceInput = $('<input>').attr({
            type: 'hidden',
            id: sourceName,
            name: sourceName,
            value: sourceName
        });

        $('#MultiActionForm').append(sourceInput);
        $('.alert').hide();
        $.ajax({
            type: "POST",
            url: "@Url.Action("MultiAction", "Aliquots")",
            data: $('#MultiActionForm').serialize(),
        datatype: "html",
        success: function (data) {
            var printWindow = window.open();
            printWindow.document.open('text/plain')
            printWindow.document.write(data);
            printWindow.document.close();
            printWindow.focus();
            printWindow.print();
            printWindow.close();
        },
        error: function () {
        }
    });
    }

    function onResetClick()
    {
        $.ajax({
            type: "POST",
            url: "@Url.Action("MultiAction", "Aliquots")",
            data: $('#MultiActionForm').serialize(),
        datatype: "html",
        success: function (data) {
            //$.ajaxSettings.traditional = true;
            $.ajax({
                contentType: "text/html; charset=utf-8",
                type: "GET",
                url: data.url + "/RESET/",
                success: function (dataR) {
                    $('.alert').hide();
                },
                error: function (respE) {
                    $('#printerrortext').text("Error resetting the printer bridge");
                }
            });
        },
        error: function () {
            $('#printerrortext').text("Error getting printer information from server");
            $('.alert').show();
        }
    });
    }
</script>

@{ Html.RenderPartial("_Dialog"); }

@using (Html.BeginForm("MultiAction", "Aliquots", FormMethod.Post, new { id = "MultiActionForm" }))
{
    @Html.Hidden("ParentId", (object)ViewBag.IsolateId)
    <div id="checkboxes">
        <table class="table">
            <tr>
                <td colspan="7"><table><tr>
                <td style="padding-left: 20px">
                    <div class="btn-group">
                        <button data-loading-text="Transmit" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                            Transmit<span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#" onclick="onDownloadClick(this.name);" name="submitDLSTrs" type="submit" class="btn btn-default" data-loading-text="Specimens">Specimens</a></li>
                            <li><a href="#" onclick="onDownloadClick(this.name);" name="submitDLATrs" type="submit" class="btn btn-default" data-loading-text="Aliquots">Aliquots</a></li>
                        </ul>
                    </div>
                </td>
               <td>
                   <button data-loading-text="Print Labels" name="submitPL" type="button" class="btn btn-default" onclick="onPrintClick(this.name);">Print Labels</button>
                   <button data-loading-text="Print Labels (Dialog)" name="submitPLP" type="button" class="btn btn-default" onclick="onPrintClick_Dialog(this.name);">Print Labels (Dialog)</button>
               </td>
                                           <td colspan="4" style="padding-left: 20px">
                                               <div class="alert alert-danger" style="display: none">
                                                   <a aria-label="close" class="close" onclick="$('.alert').hide()">&times;</a>
                                                   <div id="printerror">
                                                       <span id="printerrortext"></span>
                                                       <br />
                                                       <button data-loading-text="Reset" type="button" class="btn btn-warning btn-xs" onclick="onResetClick();">Reset</button>
                                                   </div>
                                               </div>
                                           </td>    
                </tr></table>
            </td>
            </tr>
            <tr>
                <th><input type="checkbox" id="checkall" /></th>
                <th>
                    @Html.DisplayNameFor(model => model.CSID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.SubType)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.CUID)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.TestCode)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Manifest)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.IsStoredLocallyDisplay)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Status)
                </th>
                <th></th>
            </tr>
            @{var items = Model.ToList();}
            @for (int i = 0; i < items.Count; i++)
            {
                var item = items[i];
                <tr>
                    <td style="text-align:center">
                        @Html.Hidden("Items[" + (@i) + "].Id", item.Id)
                        @Html.CheckBox("Items[" + (@i) + "].Selected", item.Selected)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CSID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.SubType)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CUID)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.TestCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Manifest)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IsStoredLocallyDisplay)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Status)
                    </td>
                    <td>
                        <table>
                            <tr>
                                <td style="padding-left: 5px">
                                                                        @if (item.AllowRUD)
                                                                            {@Html.ActionLink("Edit", "Edit", new { id = item.Id })}
</td>
                                <td style="padding-left: 5px">@Html.ActionLink("Details", "Details", new { id = item.Id })</td>
                                <td style="padding-left: 5px">
                                                                        @if (item.AllowRUD)
                                                                            {@Html.ActionLink("Delete", "Delete", new { id = item.Id })}
</td>
                            </tr>
                        </table>
                    </td>
                </tr>
}
        </table>
        <p>
            @Html.ActionLink("Go to Sub Sample Details", "Details", "Isolates", new { id = ViewBag.IsolateId }, null)
</p>
    </div>
        }
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/ContractLab")
    @if (!String.IsNullOrEmpty(ViewBag.DialogTitle))
    {
        <script type="text/javascript">
            $('#dialogModal').modal('show');
        </script>
    }
}