ContractLab/ContractLab.UI/Controllers/CategoryController.cs
using ContractLab.DTO;
using ContractLab.UI.Models.ContractLab;
using ContractLab.DataService;
using ContractLab.DataService.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Yahara.ServiceInfrastructure.Messages;

namespace ContractLab.UI.Controllers
{
    public class CategoryController : Controller
    {
        private readonly IContractLabDataService _dataService;
        public CategoryController(IContractLabDataService dataService)
        {
            _dataService = dataService;
        }

        // GET: Category
        public ActionResult Index()
        {
            int? localpage = null;
            int? DefaultPageSize = int.MaxValue;
            var vm = new List<CategoryVM>();
            var requestdetail = new RequestDetail() { CurrentPage = localpage ?? 1, ItemsPerPage = DefaultPageSize.Value };
            var dto = _dataService.CategoryList(new MessageBase<RequestDetail>() { Data = requestdetail});
            if (dto.Success)
            {
                foreach (var item in dto.Data)
	            {
                    vm.Add(new CategoryVM(item));
	            }                
            }
            return View(vm);
        }

        // GET: Category/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryVM vm = null;
            var dto = _dataService.Category(new MessageBase<int>() { Data = id.Value });
            if (dto.Success)
            {
                vm = new CategoryVM(dto.Data);
            }
            else
            {
                return HttpNotFound();
            }
            return View(vm);
        }

        // POST: Category/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, [Bind(Include = "Id")] CategoryVM vm)
        {
            var result = _dataService.CategoryDelete(new MessageBase<int>() { Data = id });
            if (result.Success)
            {
                return RedirectToAction("Index");
            }
            else
            {
                vm = null;
                var dto = _dataService.Category(new MessageBase<int>() { Data = id });
                if (dto.Success)
                {
                    vm = new CategoryVM(dto.Data);
                }
                else
                {
                    return HttpNotFound();
                }
                return View(vm);
            }
        }

        // GET: Category/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Category/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, AllowBlank, LitsQuestionId")] CategoryVM vm)
        {
            if (ModelState.IsValid)
            {
                var dto = new CategoryDTO { Name = vm.Name,  AllowBlank = vm.AllowBlank, Description = vm.Name, LitsQuestionId = vm.LitsQuestionId };
                var project = _dataService.CategoryInsert(new MessageBase<CategoryDTO>() { Data = dto });
                if (project.Success)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(vm);
        }

        // GET: Category/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CategoryVM vm = null;
            var dto = _dataService.Category(new MessageBase<int>() { Data = id.Value });
            if (dto.Success)
            {
                vm = new CategoryVM(dto.Data);
            }
            else
            {
                return HttpNotFound();
            }
            return View(vm);
        }

        // POST: Category/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Name, AllowBlank, LitsQuestionId")] CategoryVM vm)
        {
            if (ModelState.IsValid)
            {
                var dto = new CategoryDTO { Id = vm.Id, Name = vm.Name, AllowBlank = vm.AllowBlank, Description = vm.Name, LitsQuestionId = vm.LitsQuestionId };
                var project = _dataService.CategoryEdit(new MessageBase<CategoryDTO>() { Data = dto });
                if (project.Success)
                {
                    return RedirectToAction("Index");
                }
            }
            return View(vm);
        }

    }
}

ContractLab/ContractLab.UI/Controllers/SynonymController.cs
using ContractLab.DTO;
using ContractLab.UI.Models.ContractLab;
using ContractLab.DataService;
using ContractLab.DataService.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Yahara.ServiceInfrastructure.Messages;

namespace ContractLab.UI.Controllers
{
    public class SynonymController : Controller
    {
        private readonly IContractLabDataService _dataService;
        public SynonymController(IContractLabDataService dataService)
        {
            _dataService = dataService;
        }

        // GET: Condition
        public ActionResult Index(int? id)
        {
            var condition = _dataService.Condition(new MessageBase<int>() { Data = id.Value });
            if (condition.Success)
            {
                ViewBag.ConditionId = id;
                ViewBag.CategoryId = condition.Data.CategoryId;
            }
            var vm = new List<SynonymVM>();
            var dto = _dataService.SynonymList(new MessageBase<int>() { Data = id.Value });
            if (dto.Success)
            {
                foreach (var item in dto.Data)
	            {
                    vm.Add(new SynonymVM(item));
	            }                
            }
            return View(vm);
        }

        // GET: Aliquots/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ViewBag.CategoryId = id;
            SynonymVM vm = null;
            var dto = _dataService.Synonym(new MessageBase<int>() { Data = id.Value });
            if (dto.Success)
            {
                vm = new SynonymVM(dto.Data);
            }
            else
            {
                return HttpNotFound();
            }
            return View(vm);
        }

        // POST: Aliquots/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, [Bind(Include = "Id, CategoryId, ConditionId")] SynonymVM vm)
        {
            var result = _dataService.SynonymDelete(new MessageBase<int>() { Data = id });
            if (result.Success)
            {
                return RedirectToAction("Index", new { id = vm.ConditionId });
            }
            else
            {
                vm = null;
                var dto = _dataService.Synonym(new MessageBase<int>() { Data = id });
                if (dto.Success)
                {
                    vm = new SynonymVM(dto.Data);
                }
                else
                {
                    return HttpNotFound();
                }
                
                return View(vm);
            }
        }

        // GET: Synonym/Create
        public ActionResult Create(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var vm = new SynonymVM() { ConditionId = id.Value };
            var condition = _dataService.Condition(new MessageBase<int>() { Data = id.Value });
            if (condition.Success)
            {
                vm.CategoryId = condition.Data.CategoryId;
                vm.ConditionName = condition.Data.Name;
                vm.ConditionId = condition.Data.Id;
                vm.LitsQuestionId = condition.Data.LitsQuestionId;
                vm.Status = condition.Data.Status;
            }
            return View(vm);
        }

        // POST: Synonym/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Name, CategoryId, ConditionId, LitsQuestionId, Sorter, Status, ConditionName")] SynonymVM vm)
        {
            if (ModelState.IsValid)
            {
                var dto = new SynonymDTO { Name = vm.Name, CategoryId = vm.CategoryId, ConditionId = vm.ConditionId, LitsQuestionId = vm.LitsQuestionId, Status = vm.Status, ConditionName = vm.ConditionName };
                var project = _dataService.SynonymInsert(new MessageBase<SynonymDTO>() { Data = dto });
                if (project.Success)
                {
                    return RedirectToAction("Index", new { id = vm.ConditionId });
                }
                else
                {
                    ModelState.AddModelError("", project.GetDetailedErrorString());
                }
            }
            return View(vm);
        }

        // GET: Synonym/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SynonymVM vm = null;
            var dto = _dataService.Synonym(new MessageBase<int>() { Data = id.Value });
            if (dto.Success)
            {
                vm = new SynonymVM(dto.Data);
            }
            else
            {
                return HttpNotFound();
            }
            return View(vm);
        }

        // POST: Synonym/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id, Name, CategoryId, ConditionId, LitsQuestionId, Sorter, Status")] SynonymVM vm)
        {
            if (ModelState.IsValid)
            {
                var dto = new SynonymDTO { Id = vm.Id, Name = vm.Name, CategoryId = vm.CategoryId, ConditionId = vm.ConditionId, LitsQuestionId = vm.LitsQuestionId, Status = vm.Status };
                var project = _dataService.SynonymEdit(new MessageBase<SynonymDTO>() { Data = dto });
                if (project.Success)
                {
                    return RedirectToAction("Index", new { id = vm.ConditionId });
                }
                else
                {
                    ModelState.AddModelError("", project.GetDetailedErrorString());
                }
            }
            return View(vm);
        }

    }
}

ContractLab/ContractLab.UI/Views/Condition/Create.cshtml
@model ContractLab.UI.Models.ContractLab.ConditionVM

@{
    ViewBag.Title = "Condition";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Condition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LitsQuestionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LitsQuestionId, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LitsQuestionId, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sorter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sorter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sorter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.CategoryId })
</div>

ContractLab/ContractLab.UI/Views/Condition/Delete.cshtml
@model ContractLab.UI.Models.ContractLab.ConditionVM

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Condition</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LitsQuestionId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LitsQuestionId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CategoryId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SynonymsCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SynonymsCount)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.HiddenFor(model => model.CategoryId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ActionLink("Back to List", "Index", "Condition", new { id = ViewData.Model.CategoryId }, null)
        </div>
    }
</div>

ContractLab/ContractLab.UI/Views/Condition/Edit.cshtml
@model ContractLab.UI.Models.ContractLab.ConditionVM

@{
    ViewBag.Title = "Condition";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Condition</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CategoryName, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CategoryName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LitsQuestionId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LitsQuestionId, new { htmlAttributes = new { @readonly = "readonly", @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LitsQuestionId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Status, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Status, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Status, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sorter, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Sorter, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Sorter, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index", new { id = Model.CategoryId })
</div>

ContractLab/ContractLab.UI/Views/Condition/Index.cshtml
@model IEnumerable<ContractLab.UI.Models.ContractLab.ConditionVM>

@{
    ViewBag.Title = "Conditions";
}

<h2>Conditions</h2>
<p>
    @Html.ActionLink("Create New", "Create", new { id = ViewBag.CategoryId })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LitsQuestionId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sorter)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SynonymsCount)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LitsQuestionId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Status)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sorter)
        </td>
        <td>
            @Html.ActionLink(item.SynonymsCount.ToString(), "Index", "Synonym", new { id = item.Id }, null)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) | @Html.ActionLink("Delete", "Delete", new { id = item.Id })
        </td>
    </tr>
}

</table>
<p>
    @Html.ActionLink("Go to Categories", "Index", "Category", null, null)
</p>